obj-$(CONFIG_OPPO_COMMON_SOFT)	+=  oppo_project/
obj-$(CONFIG_OPPO_DEVICE_IFNO)	+=  oppo_devinfo/
obj-$(CONFIG_RECORD_MDMRST)     +=  oppo_mdmrst/
#ifdef VENDOR_EDIT
#//jie.cheng@swdh.sh, 2016/04/15, Add hypnus helper
obj-y     +=  oppo_hypnus/
#//wenbin.liu@PSW.Kernel.MM, 2018/05/23, Add for Healthinfo monitor
#obj-y     +=  oppo_healthinfo/
#endif /* VENDOR_EDIT */
#obj-y     +=  oppo_BScheck/
obj-y     +=  oppo_als_cali_value/

